# @package _group_
experiment: default
# experimental settings
n_seeds: 100
dataset: eurlex # wiki or eurlex
n_val_data: 2000
beta: 30
eps: 0.1
max_reward_noise: 0.2
random_state: 123
# estimator hyper-param
n_clusters: 100
# varying configs
n_val_data_list:
  - 1000
  - 2000
  - 4000
  - 8000
