defaults:
  - setting: default
hydra:
  run:
    dir: ./synthetic/logs/n_val=${setting.n_val_data},n_actions=${setting.n_actions}/reward_type=${setting.reward_type}/n_emb=${setting.n_cat_per_dim},n_cat_dim=${setting.n_cat_dim},n_clus=${setting.n_clusters},noise=${setting.reward_std}/beta=${setting.beta},eps=${setting.eps}
  sweep:
    dir: ./synthetic/logs/n_val=${setting.n_val_data},n_actions=${setting.n_actions}/reward_type=${setting.reward_type}/n_emb=${setting.n_cat_per_dim},n_cat_dim=${setting.n_cat_dim},n_clus=${setting.n_clusters},noise=${setting.reward_std}/beta=${setting.beta},eps=${setting.eps}
    subdir: ./
